apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
  namespace: evelyn-dev
spec:
  entrypoint: hello
  templates:
    - name: hello
      steps:
      - - name: hello-01
          template: whalesay
          arguments:
            parameters: [{name: message, value: "hello1"}]

        - name: hello-02
          template: whalesay
          arguments:
            parameters: [{name: message, value: "hello1"}]

      - - name: hello-11
          template: whalesay
          arguments:
            parameters: [{name: message, value: "hello1"}]

        - name: hello-12
          template: whalesay
          arguments:
            parameters: [{name: message, value: "hello1"}]

    - name: whalesay
      inputs:
        parameters:
        - name: message
          value: hello world
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
