apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template
  namespace: evelyn-dev
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      inputs:
        parameters:
        - name: message
          value: hello world
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
