apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: recommender-engine
build:
  artifacts:
  - image: gcr.io/personal-351003/recommender-engine
    docker:
      dockerfile: recommender/Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/recommender-engine.yaml
