apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-backend
  labels:
    app: recommender-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: recommender-backend
  template:
    metadata:
      labels:
        app: recommender-backend
    spec:
      containers:
      - name: recommender-backend
        image: gcr.io/personal-351003/recommender-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_USERNAME
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recommender-mongodb
              key: mongodb-root-password
        - name: MONGODB_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_HOST
      volumes:
      - name: recommender-config
        configMap:
          name: recommender-config
      - name: recommender-mongodb-secret
        secret:
          secretName: recommender-mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: recommender-backend
spec:
  selector:
    app: recommender-backend
  ports:
  - port: 3001
    targetPort: 3001

