apiVersion: v1
kind: ConfigMap
metadata:
  name: recommender-config
data:
  POSTGRES_DB_USERNAME: admin
  POSTGRES_DB_HOST: mlflow-db-postgresql
  POSTGRES_DB_PORT: "5432"
  POSTGRES_DB_NAME: mlflow-tracking-server-db
  GCP_PROJECT_ID: personal-351003
  ARTIFACT_URI: gs://personal-mlflow-tracking/artifacts
  BACKEND_HOST: backend
  BACKEND_PORT: "3000"
  BACKEND_USERNAME: aarongrainer
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  RECOMMENDER_ENGINE_HOST: recommender-engine
  RECOMMENDER_ENGINE_PORT: "4000"
  MONGODB_ROOT_USERNAME: root
  MONGODB_ROOT_HOST: mongodb
  KAFKA_HOST: kafka-service
  KAFKA_PORT: "9092"
