apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/personal-351003/kubernetes-devops-frontend:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP
        env:
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: BACKEND_HOST
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: BACKEND_PORT
        - name: BACKEND_USERNAME
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: BACKEND_USERNAME
        - name: BACKEND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recommender-secret
              key: BACKEND_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: recommender-secret
              key: SECRET_KEY
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: KAFKA_PRODUCER_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: KAFKA_PRODUCER_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: KAFKA_PORT
      volumes:
      - name: recommender-config
        configMap:
          name: recommender-config
      - name: recommender-secret
        secret:
          secretName: recommender-secret

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 8501
    targetPort: 8501

