apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-engine
  labels:
    app: recommender-engine
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: recommender-engine
  template:
    metadata:
      labels:
        app: recommender-engine
    spec:
      containers:
      - name: recommender-engine
        image: gcr.io/personal-351003/recommender-engine:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "3Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
        env:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: POSTGRES_DB_USERNAME
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-db-postgresql
              key: postgres-password
        - name: POSTGRESQL_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: POSTGRES_DB_HOST
        - name: POSTGRESQL_PORT
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: POSTGRES_DB_PORT
        - name: POSTGRESQL_MLFLOW_DB
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: POSTGRES_DB_NAME
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_USERNAME
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        - name: MONGODB_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_HOST
      volumes:
      - name: recommender-config
        configMap:
          name: recommender-config
      - name: mlflow-db-postgresql-secrect
        secret:
          secretName: mlflow-db-postgresql
      - name: mongodb-secret
        secret:
          secretName: mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: recommender-engine
spec:
  selector:
    app: recommender-engine
  ports:
  - port: 4000
    targetPort: 4000

