apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-engine
  labels:
    app: recommender-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender-engine
  template:
    metadata:
      labels:
        app: recommender-engine
    spec:
      containers:
      - name: recommender-engine
        image: gcr.io/personal-351003/recommender-engine:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "3Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: DB_USERNAME
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-db-postgresql
              key: postgres-password
        - name: POSTGRESQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: DB_HOST
        - name: POSTGRESQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: DB_PORT
        - name: POSTGRESQL_MLFLOW_DB
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: DB_NAME
      volumes:
      - name: mlflow-config
        configMap:
          name: mlflow-config
      - name: mlflow-db-postgresql-secrect
        secret:
          secretName: mlflow-db-postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: recommender-engine
spec:
  selector:
    app: recommender-engine
  ports:
  - port: 3000
    targetPort: 3000

