apiVersion: batch/v1
kind: Job
metadata:
  name: script
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: script
        image: gcr.io/personal-351003/recommender-script:latest
        command: ["python", "-m", "scripts.cli", "upload-new-movie-list"]
        env:
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_USERNAME
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recommender-mongodb
              key: mongodb-root-password
        - name: MONGODB_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: recommender-config
              key: MONGODB_ROOT_HOST
      restartPolicy: Never
      volumes:
      - name: recommender-config
        configMap:
          name: recommender-config
      - name: recommender-mongodb-secret
        secret:
          secretName: recommender-mongodb

