apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: gcr.io/personal-351003/kubernetes-devops-backend
    docker:
      dockerfile: backend/Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/backend.yaml
