apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: recommender-frontend
build:
  artifacts:
  - image: gcr.io/personal-351003/recommender-frontend
    docker:
      dockerfile: frontend/Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/frontend.yaml
